name: Build and Release

on:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [aarch64-apple-darwin]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      
      - name: Check lint
        run: cargo clippy

      # Disabled for now, since FUSE tests cannot run in default test runners
      # - name: Run tests
      #   run: cargo test

      - name: Build binary
        run: |
          cargo build --release --target ${{ matrix.target }}
          strip target/${{ matrix.target }}/release/treebeard || true
          
      - name: Prepare release archive
        run: |
          cd target/${{ matrix.target }}/release
          tar -czf treebeard-${{ matrix.target }}.tar.gz treebeard
          
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: target/${{ matrix.target }}/release/treebeard-${{ matrix.target }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  trigger-homebrew-update:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Trigger Homebrew Tap Update
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: divmain/homebrew-treebeard
          event-type: update_needed
          client-payload: '{"version":"${{ github.ref_name }}","tag":"${{ github.ref_name }}"}'
